models/TmForeign.php
<?php

namespace app\models;

use Yii;
use yii\imagine\Image;
use Imagine\Image\Box;
use Imagine\Exception\RuntimeException;
use app\components\RequestAndTMModel;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "tm_foreign".
 *
 * @property integer $id
 * @property string $name
 * @property string $st13
 * @property integer $app_number
 * @property string $app_language
 * @property string $app_date
 * @property string $reg_office
 * @property integer $reg_number
 * @property string $img
 * @property integer $captcha_id
 * @property string $reg_date
 * @property string $expiry_date
 * @property integer $base_app_number
 * @property integer $base_reg_number
 * @property string $base_app_date
 * @property string $base_reg_date
 * @property string $owner
 * @property string $address
 * @property integer $type_id
 * @property integer $kind_id
 * @property integer $status_id
 * @property string $update_time
 *
 */
class TmForeign extends RequestAndTMModel {
    
    public $rank;

    public static function tableName() {
        return 'tm_foreign';
    }

    public function getCountries() {
        return $this->hasMany(TmForeignCountry::className(), ['tm_id' => 'id']);
    }

    public function getStatus() {
        return $this->hasOne(ForeignStatus::className(), ['id' => 'status_id']);
    }

    public function getType() {
        return $this->hasOne(TmType::className(), ['id' => 'type_id']);
    }

    public function getKind() {
        return $this->hasOne(KindOfMark::className(), ['id' => 'kind_id']);
    }

    public function getClasses() {
        return $this->hasMany(TmForeignClass::className(), ['tm_id' => 'id'])
            ->with('class');
    }

    public function getThumb() {
        if (file_exists($this->img) && exif_imagetype($this->img)) {
            $tmbPath = substr($this->img, 0, strpos($this->img, '.'));
            $ext = substr($this->img, strpos($this->img, '.'));
            $tmbPath .= "_tmb$ext";
            if (!file_exists($tmbPath)) {
                try {
                    Image::getImagine()->open($this->img)->thumbnail(new Box(130, 100))->save($tmbPath , ['quality' => 90]);
                } catch (RuntimeException $e) {

                }
            }
            return $tmbPath;
        }
        return NULL;
    }

    public static function getRecognizedAndEmpty($limit = false, $dataProvider = false) {
        $requestTerms = TmForeignTerm::find()
            ->select('tm_id')->groupBy('tm_id');

        $query = self::find()
            ->where(['and',
                ['not', ['img' => null]],
                ['>', 'captcha_id', 0],
                ['not in', 'id', $requestTerms]
            ])->orderBy(['id' => SORT_DESC]);

        if ($limit) {
            $query->limit($limit);
        }

        if ($dataProvider) {
            $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'pageSize' => 20,
                ],
            ]);
            return $dataProvider;
        }
        return $query->all();
    }

    public static function getCountRecognizedAndEmpty() {
        $trademarkTerms = TmForeignTerm::find()
            ->select('tm_id')->groupBy('tm_id');

        return self::find()
            ->where(['and',
                ['not', ['img' => null]],
                ['>', 'captcha_id', 0],
                ['not in', 'id', $trademarkTerms]
            ])
            ->count();
    }

}

controllers/RospatentController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Requests;
use app\models\Trademarks;
use yii\web\HttpException;


class RospatentController extends Controller {

    public function actionIndex() {
        
    }

    public function actionZayavka($number) {
        $request = Requests::findOne(['request_number' => $number]);
        $classes = [];

        if (!empty($request)) {
            if (!empty($request->classes)) {
                $classes = unserialize($request->classes);
            }
            return $this->render('zayavka', [
                'request' => $request,
                'classes' => $classes
            ]);
        } else {
            throw new HttpException(404 ,'По данному запросу ничего не найдено!');
        }
    }

    public function actionZnak($number) {
        $slash = false;
        $classes = [];
        $numberArr = explode('/', $number);

        if (!empty($numberArr[1])) {
            $slash = $numberArr[1];
            $number = $numberArr[0];
        }

        if ($slash) {
            $trademark = Trademarks::findOne(['reg_number' => $number . '/' . $slash]);
        } else {
            $trademark = Trademarks::findOne(['reg_number' => $number]);
        }

        if (!empty($trademark)) {
            if (!empty($trademark->classes)) {
                $classes = unserialize($trademark->classes);
            }
            return $this->render('znak', [
                'trademark' => $trademark,
                'classes' => $classes
            ]);
        } else {
            throw new HttpException(404 ,'По данному запросу ничего не найдено!');
        }
    }

}

views/rospatent/zayavka.php
<?php if (!empty($request)) { ?>
    <?php $this->title = 'Заявка на товарный знак №' . $request->request_number . ' в системе Monocle'; ?>
    <div class="single">
        <?php if (!empty($request->img)) { ?>
            <img class="preview" src="/<?php echo $request->img; ?>" height="50"/>
        <?php } ?>
        <h1>Заявка на товарный знак №<?php echo $request->request_number; ?></h1>
        <p><i>Номер заявки:</i> <b><?php echo $request->request_number; ?></b></p>
        <p><i>Номер регистрации:</i> <b><?php echo $request->reg_number; ?></b></p>
        <p><i>Дата государственной регистрации:</i> <b><?php echo $request->reg_date; ?></b></p>
        <p><i>Дата поступления заявки:</i> <b><?php echo $request->request_date; ?></b></p>
        <p><i>Заявитель:</i> <b><?php echo $request->applicant; ?></b></p>
        <p><i>Статус:</i> <b><?php echo $request->status->title; ?></b></p>
        <p><i>Номер первой заявки:</i> <b><?php echo $request->first_request_number; ?></b></p>
        <p><i>Дата подачи первой заявки:</i> <b><?php echo $request->first_request_date; ?></b></p>
        <p><i>Код страны или международной организации, куда была подана первая заявка:</i> <b><?php echo $request->first_request_country; ?></b></p>
        <p><i>Адрес для переписки:</i> <b><?php echo $request->address; ?></b></p>
        <p><i>Факсимильные изображения:</i><br>
            <?php echo $request->facsimile; ?>
        </p>
        <p><i>Классы МКТУ:</i><br>
            <?php if (!empty($classes)) { ?>
        <p><?php foreach ($classes as $key => $description) { ?>
                <b><?php echo $key; ?></b> - <?php echo $description; ?><br>
            <?php } ?>
        </p>
    <?php } ?>
        </p>
    </div>
<?php } ?>

views/rospatent/znak.php
<?php if (!empty($trademark)) { ?>
<div class="single">
    <?php if (!empty($trademark->img)) { ?>
        <img src="/<?php echo $trademark->img; ?>" height="50"/>
    <?php } ?>
    <?php $this->title = 'Товарный знак №' . $trademark->reg_number . ' в системе Monocle'; ?>
    <h1>Товарный знак №<?php echo $trademark->reg_number; ?></h1>
    <p><i>Номер заявки:</i> <b><?php echo $trademark->request_number; ?></b></p>
    <p><i>Номер регистрации:</i> <b><?php echo $trademark->reg_number; ?></b></p>
    <p><i>Дата государственной регистрации:</i> <b><?php echo $trademark->reg_date ?></b></p>
    <p><i>Дата поступления заявки:</i> <b><?php echo $trademark->request_date ?></b></p>
    <p><i>Дата публикации:</i> <b><?php echo $trademark->publish_date ?></b></p>
    <p><i>Дата истечения срока действия регистрации:</i> <b><?php echo $trademark->reg_expiry_date ?></b></p>
    <p><i>Дата прекращения правовой охраны товарного знака:</i> <b><?php echo $trademark->legal_protection_end_date ?></b></p>
    <p><i>Статус:</i> <b><?php echo $trademark->status->title ?></b></p>
    <p><i>Последнее изменение статуса:</i> <b><?php echo $trademark->status_date ?></b></p>
    <p><i>Приоритет:</i> <b><?php echo $trademark->priority ?></b></p>
    <p><i>Указание цвета или цветового сочетания:</i> <b><?php echo $trademark->colors ?></b></p>
    <p><i>Номер первой заявки:</i> <b><?php echo $trademark->first_request_number ?></b></p>
    <p><i>Дата подачи первой заявки:</i> <b><?php echo $trademark->first_request_date ?></b></p>
    <p><i>Код страны или международной организации, куда была подана первая заявка:</i> <b><?php echo $trademark->first_request_country ?></b></p>
    <p><i>Наименование лицензиата:</i> <b><?php echo $trademark->licensee ?></b></p>
    <p><i>Дата и номер регистрации договора:</i> <b><?php echo $trademark->contract_date ?>&nbsp;<?php echo $trademark->contract_number ?></b></p>
    <p><i>Указание условий и/или ограничений лицензии:</i> <b><?php echo $trademark->license_terms ?></b></p>
    <p><i>Правообладатель:</i> <b><?php echo $trademark->rightholder ?></b></p>
    <p><i>Адрес для переписки:</i> <b><?php echo $trademark->address ?></b></p>
    <p><i>Классы МКТУ:</i><br>
    <?php if (!empty($classes)) { ?>
        <p><?php foreach ($classes as $key => $description) { ?>
                <b><?php echo $key; ?></b> - <?php echo $description; ?><br>
            <?php } ?>
        </p>
    <?php } ?>
    </p>
</div>
<?php } ?>